---
- name: Deploy Joplin stack
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
  vars:
    app_dir: /opt/stacks/joplin

  tasks:
    - name: Ensure Docker prerequisites are installed
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Create app directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: "0755"

    - name: Copy Joplin docker compose file
      ansible.builtin.copy:
        src: ../apps/joplin/docker-compose.yml
        dest: "{{ app_dir}}/docker-compose.yml"
        mode: "0644"

    - name: Install .env
      template:
        src: .env.j2
        dest: "{{ app_dir}}/.env"
        owner: root
        group: root
        mode: "0600"

    - name: Start Joplin stack
      ansible.builtin.command:
        chdir: "{{ app_dir }}"
        cmd: docker compose -f docker-compose.yml up -d
      register: compose_result
      changed_when: "'Creating' in compose_result.stdout or 'Recreating' in compose_result.stdout or 'Starting' in compose_result.stdout"

    - name: Create joplin site config
      ansible.builtin.copy:
        dest: /etc/nginx/locations.d/joplin.conf
        mode: "0644"
        content: |
          location /joplin/ {
            rewrite ^/joplin/(.*)$ /$1 break;
            proxy_pass http://127.0.0.1:22300/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port 443;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 600s;
            proxy_send_timeout 600s;
            proxy_redirect off;
          }

          location = /joplin {
            return 301 /joplin/;
          }
        notify: Reload nginx

  handlers:
    - ansible.builtin.import_tasks: handlers/nginx.yml
